### ISSUE TITLE
Cache key must be string, "NULL" given

### ISSUE THREAD

**Issue by quique0194** [bitnami/bitnami-docker-prestashop#91]
I try to run the docker-compose bitnami version of prestashop and I keep getting the following error: Cache key must be string, "NULL" given

**Steps to reproduce the issue:**

1. curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-prestashop/master/docker-compose.yml > docker-compose.yml
2. docker-compose up
3. Go to http://localhost/ and it will be a white page. In the logs, this is the error:

```
prestashop_1  | mysql-c INFO  Found MySQL server listening at mariadb:3306
prestashop_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
prestashop_1  | prestas INFO  Configuring PrestaShop...
prestashop_1  | prestas INFO 
prestashop_1  | prestas INFO  ########################################################################
prestashop_1  | prestas INFO   Installation parameters for prestashop:
prestashop_1  | prestas INFO     First Name: Bitnami
prestashop_1  | prestas INFO     Last Name: User
prestashop_1  | prestas INFO     Email: user@example.com
prestashop_1  | prestas INFO     Password: **********
prestashop_1  | prestas INFO     Shop Name: PrestaShop
prestashop_1  | prestas INFO     Admin URL: http://localhost/administration
prestashop_1  | prestas INFO   (Passwords are not shown for security reasons)
prestashop_1  | prestas INFO  ########################################################################
prestashop_1  | prestas INFO 
prestashop_1  | nami    INFO  prestashop successfully initialized
prestashop_1  | INFO  ==> Starting gosu... 
prestashop_1  | [Thu Sep 24 04:56:59.780781 2020] [ssl:warn] [pid 136] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Sep 24 04:56:59.781114 2020] [ssl:warn] [pid 136] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Sep 24 04:56:59.802850 2020] [ssl:warn] [pid 136] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Sep 24 04:56:59.803096 2020] [ssl:warn] [pid 136] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Sep 24 04:56:59.812526 2020] [mpm_prefork:notice] [pid 136] AH00163: Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.2.31 configured -- resuming normal operations
prestashop_1  | [Thu Sep 24 04:56:59.812548 2020] [core:notice] [pid 136] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
prestashop_1  | [Thu Sep 24 04:57:25.446167 2020] [php7:error] [pid 137] [client 172.23.0.1:45838] PHP Fatal error:  Uncaught Symfony\\Component\\Cache\\Exception\\InvalidArgumentException: Cache key must be string, "NULL" given in /bitnami/prestashop/vendor/symfony/symfony/src/Symfony/Component/Cache/CacheItem.php:156\nStack trace:\n#0 /bitnami/prestashop/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/AbstractTrait.php(235): Symfony\\Component\\Cache\\CacheItem::validateKey(NULL)\n#1 /bitnami/prestashop/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php(152): Symfony\\Component\\Cache\\Adapter\\AbstractAdapter->getId(NULL)\n#2 /bitnami/prestashop/src/Core/Localization/CLDR/DataLayer/LocaleCache.php(82): Symfony\\Component\\Cache\\Adapter\\AbstractAdapter->getItem(NULL)\n#3 /bitnami/prestashop/src/Core/Data/Layer/AbstractDataLayer.php(90): PrestaShop\\PrestaShop\\Core\\Localization\\CLDR\\DataLayer\\LocaleCache->doRead(NULL)\n#4 /bitnami/prestashop/src/Core/Localization/CLDR/LocaleDataSource.php(62): PrestaShop\\PrestaShop\\Core\\Data\\Layer\\AbstractDataLayer->read(NULL)\n#5 /bitnami/prestashop/src/Core/Localization/ in /bitnami/prestashop/vendor/symfony/symfony/src/Symfony/Component/Cache/CacheItem.php on line 156
```

**Version**

- Output of `docker version`: 

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 12
  Running: 5
  Paused: 0
  Stopped: 7
 Images: 233
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-48-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.719GiB
 Name: gamemax
 ID: XXPV:OTH2:7F2S:5RTG:X37B:VALN:LNLT:DHJT:L5YV:FDJH:W6LW:G53U
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: quique0194
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.3, build 4092ae5d
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

OS Version: Ubuntu 20.04

**Comment by juan131** [comment]
Hi @quique0194 

I just followed the same steps you shared and I was not able to reproduce the issue, see the logs:

```
prestashop_1  | prestas INFO  ########################################################################
prestashop_1  | prestas INFO   Installation parameters for prestashop:
prestashop_1  | prestas INFO     First Name: Bitnami
prestashop_1  | prestas INFO     Last Name: User
prestashop_1  | prestas INFO     Email: user@example.com
prestashop_1  | prestas INFO     Password: **********
prestashop_1  | prestas INFO     Shop Name: PrestaShop
prestashop_1  | prestas INFO     Admin URL: http://localhost/administration
prestashop_1  | prestas INFO   (Passwords are not shown for security reasons)
prestashop_1  | prestas INFO  ########################################################################
prestashop_1  | prestas INFO
prestashop_1  | nami    INFO  prestashop successfully initialized
prestashop_1  | INFO  ==> Starting gosu...
prestashop_1  | [Thu Sep 24 06:41:44.900042 2020] [ssl:warn] [pid 141] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Sep 24 06:41:44.900667 2020] [ssl:warn] [pid 141] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Sep 24 06:41:44.923729 2020] [ssl:warn] [pid 141] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Sep 24 06:41:44.924242 2020] [ssl:warn] [pid 141] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Sep 24 06:41:44.933731 2020] [mpm_prefork:notice] [pid 141] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.2.33 configured -- resuming normal operations
prestashop_1  | [Thu Sep 24 06:41:44.934011 2020] [core:notice] [pid 141] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
prestashop_1  | 172.19.0.1 - - [24/Sep/2020:06:45:18 +0000] "GET / HTTP/1.1" 302 -
prestashop_1  | 172.19.0.1 - - [24/Sep/2020:06:45:18 +0000] "GET / HTTP/1.1" 200 7250
prestashop_1  | 172.19.0.1 - - [24/Sep/2020:06:45:21 +0000] "GET /img/logo.png HTTP/1.1" 200 1831
prestashop_1  | 172.19.0.1 - - [24/Sep/2020:06:45:21 +0000] "GET /themes/classic/assets/cache/theme-0bd8d5.css HTTP/1.1" 200 55275
prestashop_1  | 172.19.0.1 - - [24/Sep/2020:06:45:21 +0000] "GET /modules/ps_imageslider/images/sample-1.jpg HTTP/1.1" 200 234051
prestashop_1  | 172.19.0.1 - - [24/Sep/2020:06:45:21 +0000] "GET /modules/ps_imageslider/images/sample-2.jpg HTTP/1.1" 200 194743
prestashop_1  | 172.19.0.1 - - [24/Sep/2020:06:45:21 +0000] "GET /modules/ps_imageslider/images/sample-3.jpg HTTP/1.1" 200 352616
```

I could also access the website and browse through it:

![Screenshot 2020-09-24 at 08 49 30](https://user-images.githubusercontent.com/6740773/94110419-e87ca180-fe42-11ea-8f01-f701d5329cef.png)

Could you please retry to discard any kind of transient error?

**Comment by quique0194** [comment]
Hi @juan131 and thanks for the quick response,

I've tried to run the docker-compose configuration several times and with different versions of prestashop. I always get the same result.

I usually do:

```
docker-compose down -v    # To remove volumes as well
docker-compose up
```

I know it isn't easy to replicate this error. You can check similar cases here:

https://github.com/PrestaShop/PrestaShop/issues/15258
https://github.com/1up-lab/OneupFlysystemBundle/issues/188 (not prestashop related)
https://community.bitnami.com/t/cache-key-must-be-string-null/82575/6

Just in case, this is the docker-compose file I'm using:

```
version: '2'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.1-debian-10'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  prestashop:
    image: 'docker.io/bitnami/prestashop:1.7.6-5-debian-10-r66'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'prestashop_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
```

I can enter the running container with `docker exec` and change the files in order to get any logs you want. You could tell me where to put the logs in order to debug this. I cannot do it myself because I'm not familiar with php nor symfony nor prestashop. This is my first incursion.

From the logs, I can tell the code is trying to access the symfony cache with a null key, but I cannot find where is this call happening.

**Comment by juan131** [comment]
Hi @quique0194 

Are you able to reproduce the issue the latest version (`docker.io/bitnami/prestashop:latest`) instead of `docker.io/bitnami/prestashop:1.7.6-5-debian-10-r66`? I just want to discard it's an issue already fixed on recent versions.

**Comment by quique0194** [comment]
Yep, same error:

```
prestashop_1  | mysql-c INFO  Found MySQL server listening at mariadb:3306
prestashop_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
prestashop_1  | prestas INFO  Configuring PrestaShop...
prestashop_1  | prestas INFO 
prestashop_1  | prestas INFO  ########################################################################
prestashop_1  | prestas INFO   Installation parameters for prestashop:
prestashop_1  | prestas INFO     First Name: Bitnami
prestashop_1  | prestas INFO     Last Name: User
prestashop_1  | prestas INFO     Email: user@example.com
prestashop_1  | prestas INFO     Password: **********
prestashop_1  | prestas INFO     Shop Name: PrestaShop
prestashop_1  | prestas INFO     Admin URL: http://localhost/administration
prestashop_1  | prestas INFO   (Passwords are not shown for security reasons)
prestashop_1  | prestas INFO  ########################################################################
prestashop_1  | prestas INFO 
prestashop_1  | nami    INFO  prestashop successfully initialized
prestashop_1  | INFO  ==> Starting gosu... 
prestashop_1  | [Thu Sep 24 16:19:48.957318 2020] [ssl:warn] [pid 136] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Sep 24 16:19:48.957630 2020] [ssl:warn] [pid 136] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Sep 24 16:19:48.979562 2020] [ssl:warn] [pid 136] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Sep 24 16:19:48.979869 2020] [ssl:warn] [pid 136] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Sep 24 16:19:48.990190 2020] [mpm_prefork:notice] [pid 136] AH00163: Apache/2.4.46 (Unix) OpenSSL/1.1.1d PHP/7.2.33 configured -- resuming normal operations
prestashop_1  | [Thu Sep 24 16:19:48.990214 2020] [core:notice] [pid 136] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'



prestashop_1  | [Thu Sep 24 16:29:13.939768 2020] [php7:error] [pid 137] [client 172.20.0.1:34192] PHP Fatal error:  Uncaught Symfony\\Component\\Cache\\Exception\\InvalidArgumentException: Cache key must be string, "NULL" given in /bitnami/prestashop/vendor/symfony/symfony/src/Symfony/Component/Cache/CacheItem.php:156\nStack trace:\n#0 /bitnami/prestashop/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/AbstractTrait.php(235): Symfony\\Component\\Cache\\CacheItem::validateKey(NULL)\n#1 /bitnami/prestashop/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php(152): Symfony\\Component\\Cache\\Adapter\\AbstractAdapter->getId(NULL)\n#2 /bitnami/prestashop/src/Core/Localization/CLDR/DataLayer/LocaleCache.php(82): Symfony\\Component\\Cache\\Adapter\\AbstractAdapter->getItem(NULL)\n#3 /bitnami/prestashop/src/Core/Data/Layer/AbstractDataLayer.php(90): PrestaShop\\PrestaShop\\Core\\Localization\\CLDR\\DataLayer\\LocaleCache->doRead(NULL)\n#4 /bitnami/prestashop/src/Core/Localization/CLDR/LocaleDataSource.php(62): PrestaShop\\PrestaShop\\Core\\Data\\Layer\\AbstractDataLayer->read(NULL)\n#5 /bitnami/prestashop/src/Core/Localization/ in /bitnami/prestashop/vendor/symfony/symfony/src/Symfony/Component/Cache/CacheItem.php on line 156
prestashop_1  | 172.20.0.1 - - [24/Sep/2020:16:29:12 +0000] "GET / HTTP/1.1" 500 -
```

I unfolded the error for better reading:
```
[Thu Sep 24 16:29:13.939768 2020] [php7:error] [pid 137] [client 172.20.0.1:34192]
    PHP Fatal error: Uncaught
        Symfony\\Component\\Cache\\Exception\\InvalidArgumentException:
        Cache key must be string, "NULL" given in
        /bitnami/prestashop/vendor/symfony/symfony/src/Symfony/Component/Cache/CacheItem.php:156

        Stack trace:
        #0 /bitnami/prestashop/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/AbstractTrait.php(235):
            Symfony\\Component\\Cache\\CacheItem::validateKey(NULL)
        #1 /bitnami/prestashop/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php(152):
            Symfony\\Component\\Cache\\Adapter\\AbstractAdapter->getId(NULL)
        #2 /bitnami/prestashop/src/Core/Localization/CLDR/DataLayer/LocaleCache.php(82):
            Symfony\\Component\\Cache\\Adapter\\AbstractAdapter->getItem(NULL)
        #3 /bitnami/prestashop/src/Core/Data/Layer/AbstractDataLayer.php(90):
            PrestaShop\\PrestaShop\\Core\\Localization\\CLDR\\DataLayer\\LocaleCache->doRead(NULL)
        #4 /bitnami/prestashop/src/Core/Localization/CLDR/LocaleDataSource.php(62):
            PrestaShop\\PrestaShop\\Core\\Data\\Layer\\AbstractDataLayer->read(NULL)
        #5 /bitnami/prestashop/src/Core/Localization/ in /bitnami/prestashop/vendor/symfony/symfony/src/Symfony/Component/Cache/CacheItem.php on line 156

```

**Comment by quique0194** [comment]
I run `sudo rm -rf /var/lib/docker/*` as suggested [here](https://stackoverflow.com/questions/41871728/same-docker-image-works-on-one-machine-and-fails-on-the-other), then restarted docker service, but it still doesn't work, so it isnt' a corruption in the docker filesystem.

**Comment by juan131** [comment]
Hi @quique0194 

Let's do a final test. Could you try without using volumes? I mean , using a Docker Compose like the one below:

```yaml
version: '2'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.1-debian-10'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
  prestashop:
    image: 'docker.io/bitnami/prestashop:1.7.6-5-debian-10-r66'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
```

I think it could be related to the volumes filesystem.

**Comment by quique0194** [comment]
I got an error 500 again, a little different though. Now the screen is not blank, it shows the following:

![imagen](https://user-images.githubusercontent.com/4630204/94299702-a54b2d00-ff2d-11ea-8406-07d6bbfd9162.png)

And the logs doesn't show anything. Here is the full output for reference, the error 500 are by the end:

```
mariadb_1     | mariadb 17:29:58.65
mariadb_1     | mariadb 17:29:58.67 Welcome to the Bitnami mariadb container
mariadb_1     | mariadb 17:29:58.67 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1     | mariadb 17:29:58.67 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1     | mariadb 17:29:58.67
mariadb_1     | mariadb 17:29:58.67 INFO  ==> ** Starting MariaDB setup **
mariadb_1     | mariadb 17:29:58.70 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb_1     | mariadb 17:29:58.71 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1     | mariadb 17:29:58.74 INFO  ==> Initializing mariadb database
mariadb_1     | mariadb 17:29:58.78 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb_1     | mariadb 17:29:58.78 INFO  ==> Setting user option
mariadb_1     | mariadb 17:29:58.83 INFO  ==> Installing database
mariadb_1     | mariadb 17:30:08.86 INFO  ==> Starting mariadb in background
mariadb_1     | mariadb 17:30:10.93 INFO  ==> Configuring authentication
mariadb_1     | mariadb 17:30:10.97 INFO  ==> Running mysql_upgrade
mariadb_1     | mariadb 17:30:11.41 INFO  ==> Stopping mariadb
mariadb_1     | mariadb 17:30:14.43 INFO  ==> ** MariaDB setup finished! **
mariadb_1     |
mariadb_1     | mariadb 17:30:14.62 INFO  ==> ** Starting MariaDB **
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.46-MariaDB) starting as process 1 ...
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.
mariadb_1     |
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] InnoDB: Using Linux native AIO
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] InnoDB: Initializing buffer pool, size = 128.0M
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] InnoDB: 128 rollback segment(s) are active.
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] InnoDB: Waiting for purge to start
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.49-89.0 started; log sequence number 1616723
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1     | 2020-09-25 17:30:14 139856814536448 [Note] InnoDB: Dumping buffer pool(s) not yet started
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Warning] 'proxies_priv' entry '@% root@895a5c8be6b7' ignored in --skip-name-resolve mode.
mariadb_1     | 2020-09-25 17:30:14 139857696677696 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1     | Version: '10.1.46-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
prestashop_1  |
prestashop_1  | Welcome to the Bitnami prestashop container
prestashop_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-prestashop
prestashop_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-prestashop/issues
prestashop_1  |
prestashop_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
prestashop_1  | nami    INFO  Initializing php
prestashop_1  | nami    INFO  php successfully initialized
prestashop_1  | nami    INFO  Initializing apache
prestashop_1  | nami    INFO  apache successfully initialized
prestashop_1  | nami    INFO  Initializing mysql-client
prestashop_1  | nami    INFO  mysql-client successfully initialized
prestashop_1  | nami    INFO  Initializing prestashop
prestashop_1  | prestas INFO  Configuring webserver...
prestashop_1  | prestas INFO  Configuring PHP settings...
prestashop_1  | mysql-c INFO  Trying to connect to MySQL server
prestashop_1  | mysql-c INFO  Found MySQL server listening at mariadb:3306
prestashop_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
prestashop_1  | prestas INFO  Configuring PrestaShop...
prestashop_1  | prestas INFO
prestashop_1  | prestas INFO  ########################################################################
prestashop_1  | prestas INFO   Installation parameters for prestashop:
prestashop_1  | prestas INFO     First Name: Bitnami
prestashop_1  | prestas INFO     Last Name: User
prestashop_1  | prestas INFO     Email: user@example.com
prestashop_1  | prestas INFO     Password: **********
prestashop_1  | prestas INFO     Shop Name: PrestaShop
prestashop_1  | prestas INFO     Admin URL: http://localhost/administration
prestashop_1  | prestas INFO   (Passwords are not shown for security reasons)
prestashop_1  | prestas INFO  ########################################################################
prestashop_1  | prestas INFO
prestashop_1  | nami    INFO  prestashop successfully initialized
prestashop_1  | INFO  ==> Starting gosu...
prestashop_1  | [Fri Sep 25 17:35:00.761034 2020] [ssl:warn] [pid 135] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Fri Sep 25 17:35:00.761308 2020] [ssl:warn] [pid 135] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Fri Sep 25 17:35:00.780527 2020] [ssl:warn] [pid 135] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Fri Sep 25 17:35:00.780762 2020] [ssl:warn] [pid 135] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Fri Sep 25 17:35:00.789549 2020] [mpm_prefork:notice] [pid 135] AH00163: Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.2.31 configured -- resuming normal operations
prestashop_1  | [Fri Sep 25 17:35:00.789570 2020] [core:notice] [pid 135] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'

prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:18 +0000] "GET / HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:19 +0000] "GET /favicon.ico HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:33 +0000] "GET / HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:33 +0000] "GET / HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:34 +0000] "GET / HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:34 +0000] "GET /favicon.ico HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:34 +0000] "GET / HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:34 +0000] "GET /favicon.ico HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:35 +0000] "GET / HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:35 +0000] "GET /favicon.ico HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:35 +0000] "GET / HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:35 +0000] "GET /favicon.ico HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:35 +0000] "GET / HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:35 +0000] "GET /favicon.ico HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:36 +0000] "GET / HTTP/1.1" 500 2466
prestashop_1  | 172.18.0.1 - - [25/Sep/2020:17:46:36 +0000] "GET /favicon.ico HTTP/1.1" 500 2466
```

**Comment by juan131** [comment]
That's weird @quique0194 ... Could you please run the command below?

```console
$ docker-compose exec prestashop cat /opt/bitnami/prestashop/var/logs/prod.log
```

We might find more information about the reasons behind those 500 errors.

I tried the same Docker Compose, and I could access the site and the logs are just fine:

```
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:45 +0000] "GET / HTTP/1.1" 302 -
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:46 +0000] "GET / HTTP/1.1" 200 7225
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /img/logo.png HTTP/1.1" 200 1831
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /themes/classic/assets/cache/theme-0bd8d5.css HTTP/1.1" 200 55284
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /modules/ps_imageslider/images/sample-1.jpg HTTP/1.1" 200 260937
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /modules/ps_imageslider/images/sample-2.jpg HTTP/1.1" 200 213995
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /modules/ps_imageslider/images/sample-3.jpg HTTP/1.1" 200 413603
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /2-home_default/hummingbird-printed-t-shirt.jpg HTTP/1.1" 200 6914
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /3-home_default/the-best-is-yet-to-come-framed-poster.jpg HTTP/1.1" 200 8986
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /21-home_default/brown-bear-printed-sweater.jpg HTTP/1.1" 200 7405
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /4-home_default/the-adventure-begins-framed-poster.jpg HTTP/1.1" 200 8293
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /5-home_default/today-is-a-good-day-framed-poster.jpg HTTP/1.1" 200 8031
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /themes/classic/assets/cache/bottom-6f0bd4.js HTTP/1.1" 200 146561
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /6-home_default/mug-the-best-is-yet-to-come.jpg HTTP/1.1" 200 6609
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /7-home_default/mug-the-adventure-begins.jpg HTTP/1.1" 200 6394
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /modules/ps_banner/img/sale70.png HTTP/1.1" 200 286053
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /8-home_default/mug-today-is-a-good-day.jpg HTTP/1.1" 200 5994
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /themes/classic/assets/css/19c1b868764c0e4d15a45d3f61250488.woff2 HTTP/1.1" 200 161480
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /themes/classic/assets/css/570eb83859dc23dd0eec423a49e147fe.woff2 HTTP/1.1" 200 44300
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:33:49 +0000] "GET /themes/classic/assets/css/199038f07312bfc6f0aabd3ed6a2b64d.woff2 HTTP/1.1" 200 160208
prestashop_1  | 172.19.0.1 - - [28/Sep/2020:06:34:17 +0000] "GET /index.php?r=web%2Fpwa-service-worker%2Findex&v=1593076259 HTTP/1.1" 302 -
```

**Comment by marcosbc** [comment]
Hi @quique0194, just letting you know that we have released a major change to the Bitnami PrestaShop container that may have fixed this issue. Find out more here: [1.7.6-8-debian-10-r1](https://github.com/bitnami/bitnami-docker-prestashop#176-8-debian-10-r1).
